---
name: Personas y barrios - qué anda, qué no, cuánto da
locale: es
type: learning
beta: false
teacher_info: ''
language: wollok
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
private: false
