---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No anda ninguna de las dos, no puede resolver `juan.nombre()`.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La primera sí anda, devuelve 33. La segunda no anda.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La primera sí anda, devuelve `"juan5"`. La segunda no anda.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La primera no anda. La segunda sí anda, deveulve 9.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La primera no anda. La segunda sí anda, devuelve `"juan5"`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Funcionan las dos, devuelven `"juan5"` y 9 respectivamente.
  checked: false
name: El nombre de Juan ¿más 4?
