---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Funciona, el resultado es ` "juan4"`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Funciona, el resultado es `32`
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Funciona, el resultado es `39`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No funciona, porque al objeto `juan`  no se le puede enviar el mensaje `edad()`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No funciona, da error al sumar lo que devuelve `juan.edad()`  con `4`
  checked: false
name: La edad más 4
