---
tags: []
layout: input_kids
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Funciona, el resultado es ` "juan4"`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Funciona, el resultado es `32`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Funciona, el resultado es `39`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No funciona, porque al objeto `juan`  no se le puede sumar `4`
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No funciona, no sabe qué es `juan`
  checked: false
name: Juan más 4
