---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Las tres dan error.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Error - `true` - error.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Error - `false` - error.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Error - `true` - `false`.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Error - `false` - `true`.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`false` - `true` - `false`."
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`false` - `false` - `true`."
  checked: false
name: Pobladores
